import './globals.scss';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { getUser } from '../database/users';
import { ApolloClientProvider } from './ApolloClientProvider';
import Header from './components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. Checking if the sessionToken cookie exists
  const sessionCookie = (await cookies()).get('sessionToken');

  // 2. Get the current logged in user from the database using the sessionToken value
  const user = sessionCookie && (await getUser(sessionCookie.value));

  return (
    <html lang="en">
      <body>
        <Header user={user} />
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
