import './globals.scss';
import type { Metadata } from 'next';
import { ApolloClientProvider } from './ApolloClientProvider';
import Header from './components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
